#!/usr/bin/env bash
which virtualenv > /dev/null
ret=$?

if [[ -n $1 ]]
then
    if [[ $ret -ne 0 ]]
    then
        pip install virtualenv  
    fi 
    virtualenv .
    ./bin/pip install -r requirements.txt
else
    if [[ $1 == "install" ]]
    then
        cp clack.py ~/.local/bin
    fi
fi
